recipe: default.v1

assistant_id: 20240906-223245-mad-synth
language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
  # - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.4
    #hình động dự phòng
    core_fallback_action_name: "action_custom_fallback"
    enable_fallback_prediction: True



